name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Version Tag
        id: vars
        run: echo "VERSION=v${{ github.run_number }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/discoverdollarassignment:backend-${VERSION} ./backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/discoverdollarassignment:backend-latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/discoverdollarassignment:backend-${VERSION}
          docker push ${{ secrets.DOCKER_USERNAME }}/discoverdollarassignment:backend-latest

      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/discoverdollarassignment:frontend-${VERSION} ./frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/discoverdollarassignment:frontend-latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/discoverdollarassignment:frontend-${VERSION}
          docker push ${{ secrets.DOCKER_USERNAME }}/discoverdollarassignment:frontend-latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ddassignment/DiscoverDollarAssignment
            docker compose pull
            docker compose up -d